version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./logs/nginx:/logs/nginx
      - ./config/nginx/xdebug:/etc/nginx/xdebug
      - ./config/nginx/hosts:/etc/nginx/hosts
      - ./config/nginx/init.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-network
  php:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./html:/var/www/html
      - ./logs/xdebug:/logs/xdebug
      - ./config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
      - ./logs/php-fpm/:/tmp/xdebug_log
    networks:
      - php-network
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    volumes:
      - db:/var/lib/mysql
    networks:
      - php-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
      PMA_VERBOSE: db
      PMA_USER: db
      PMA_PASSWORD: db
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    restart: always
    ports:
      - 8080:80
    networks:
        - php-network
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - php-network
networks:
  php-network:
    driver: bridge

volumes:
  db:
